/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as EditidRouteImport } from './routes/edit$id'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharactersIdRouteImport } from './routes/characters.$id'

const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const EditidRoute = EditidRouteImport.update({
  id: '/edit$id',
  path: '/edit$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/edit$id': typeof EditidRoute
  '/favoritos': typeof FavoritosRoute
  '/characters/$id': typeof CharactersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/edit$id': typeof EditidRoute
  '/favoritos': typeof FavoritosRoute
  '/characters/$id': typeof CharactersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/edit$id': typeof EditidRoute
  '/favoritos': typeof FavoritosRoute
  '/characters/$id': typeof CharactersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/edit$id' | '/favoritos' | '/characters/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/edit$id' | '/favoritos' | '/characters/$id'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/edit$id'
    | '/favoritos'
    | '/characters/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  EditidRoute: typeof EditidRoute
  FavoritosRoute: typeof FavoritosRoute
  CharactersIdRoute: typeof CharactersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit$id': {
      id: '/edit$id'
      path: '/edit$id'
      fullPath: '/edit$id'
      preLoaderRoute: typeof EditidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  EditidRoute: EditidRoute,
  FavoritosRoute: FavoritosRoute,
  CharactersIdRoute: CharactersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
