/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserCharacterIdRouteImport } from './routes/user-character.$id'
import { Route as EditIdRouteImport } from './routes/edit/$id'
import { Route as CharactersIdRouteImport } from './routes/characters.$id'

const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserCharacterIdRoute = UserCharacterIdRouteImport.update({
  id: '/user-character/$id',
  path: '/user-character/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/favoritos': typeof FavoritosRoute
  '/characters/$id': typeof CharactersIdRoute
  '/edit/$id': typeof EditIdRoute
  '/user-character/$id': typeof UserCharacterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/favoritos': typeof FavoritosRoute
  '/characters/$id': typeof CharactersIdRoute
  '/edit/$id': typeof EditIdRoute
  '/user-character/$id': typeof UserCharacterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/favoritos': typeof FavoritosRoute
  '/characters/$id': typeof CharactersIdRoute
  '/edit/$id': typeof EditIdRoute
  '/user-character/$id': typeof UserCharacterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/favoritos'
    | '/characters/$id'
    | '/edit/$id'
    | '/user-character/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/favoritos'
    | '/characters/$id'
    | '/edit/$id'
    | '/user-character/$id'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/favoritos'
    | '/characters/$id'
    | '/edit/$id'
    | '/user-character/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  FavoritosRoute: typeof FavoritosRoute
  CharactersIdRoute: typeof CharactersIdRoute
  EditIdRoute: typeof EditIdRoute
  UserCharacterIdRoute: typeof UserCharacterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-character/$id': {
      id: '/user-character/$id'
      path: '/user-character/$id'
      fullPath: '/user-character/$id'
      preLoaderRoute: typeof UserCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  FavoritosRoute: FavoritosRoute,
  CharactersIdRoute: CharactersIdRoute,
  EditIdRoute: EditIdRoute,
  UserCharacterIdRoute: UserCharacterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
